# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d414b18fc24fc7d665bbfb0a59ea4528dfb897688051bfb7ce4f168950cf9230cad0589dd5cc044fdaefcb23d14a10ac24c6992f081b227707374db60878349f

test:
  secret_key_base: 492d1fec0434460ac37c544644b99e44ab45422628fb4d0231620a310d71fc2b29cfbb3fd6c9c63386a8ff2072e416740ea22f3afd787befa6879bcf7c098f34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
